name: deploy-test
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-1
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: zip funciton
        run: zip function.zip main
      - name: confirm build&zip result
        run: ls
      - name: deploy
        run: aws lambda update-function-code --function-name watchdogs --zip-file fileb://function.zip | jq '.LastModified'
