name: deploy-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - uses: actions/checkout@v2
      - run: go version
      - run: aws help
      - name: build
        run: make build
      - run: zip function.zip main
      - run: ls
